[package]
name = "fast-cnum-converter"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fast_cnum_converter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.5" }
